[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
description = "Terminal-based REST client"
edition = "2021"
keywords = ["rest", "http", "terminal", "tui"]
license = "MIT"
name = "slumber"
repository = "https://github.com/LucasPickering/slumber"
version = "0.2.0"
# Keep in sync w/ rust-toolchain.toml
rust-version = "1.72.0"

[dependencies]
anyhow = {version = "^1.0.75", features = ["backtrace"]}
async-trait = "0.1.73"
chrono = {version = "0.4.31", default-features = false, features = ["clock", "serde", "std"]}
clap = {version = "4.4.2", features = ["derive"]}
crossterm = "0.27.0"
derive_more = "0.99.17"
dirs = "5.0.1"
futures = {version = "0.3.28", default-features = false}
indexmap = {version = "2.0.1", features = ["serde"]}
itertools = "0.11.0"
ratatui = "0.23.0"
regex = "1.9.5"
reqwest = {version = "0.11.20", default-features = false, features = ["rustls-tls"]}
rmp-serde = "1.1.2"
rusqlite = {version = "0.29.0", default-features = false, features = ["bundled", "chrono", "uuid"]}
rusqlite_migration = "1.0.2"
serde = {version = "^1.0.188", features = ["derive"]}
serde_json = {version = "1.0.107", default-features = false}
serde_json_path = "0.6.3"
serde_yaml = {version = "^0.9.25", default-features = false}
signal-hook = "0.3.17"
strum = {version = "0.25.0", default-features = false, features = ["derive"]}
thiserror = "1.0.48"
tokio = {version = "^1.32.0", default-features = false, features = ["full"]}
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.17", default-features = false, features = ["env-filter", "fmt", "registry"]}
tui-textarea = {git = "https://github.com/rhysd/tui-textarea.git", default-features = false, features = ["ratatui-crossterm"]}# Use stable after release with password
uuid = {version = "1.4.1", default-features = false, features = ["serde", "v4"]}

[dev-dependencies]
factori = "1.1.0"
rstest = {version = "0.18.2", default-features = false}
